import React,{useEffect,useState}from'react';
const API='http://127.0.0.1:8000';
const F=['land_required','affected_parcels','affected_families','legal_disputes','compensation_pending','approval_pending','documentation_pending','rehabilitation_pending','notification_pending','award_pending','possession_pending','stakeholder_responsiveness','environmental_risk','weather_risk'];
async function api(path,opt={}){const t=localStorage.getItem('survi_token');const r=await fetch(API+path,{...opt,headers:{...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{}),...(t?{Authorization:'Bearer '+t}:{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(typeof j.detail==='string'?j.detail:JSON.stringify(j.detail||j));return j}
function Login({onLogin}){const[email,setEmail]=useState('Tngov@cbe.ac.in'),[password,setPassword]=useState('Tngov@CBE#2026'),[err,setErr]=useState('');return <div className="login"><div className="loginbox"><div className="brand">SURVI</div><h2>LANDNEXUS</h2><p>Multimodal Land Acquisition Intelligence</p><input value={email}onChange={e=>setEmail(e.target.value)}placeholder="Authority email"/><input type="password"value={password}onChange={e=>setPassword(e.target.value)}placeholder="Password"/><button onClick={async()=>{try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('survi_token',x.access_token);onLogin(x.user)}catch(e){setErr(e.message)}}}>Secure Login</button>{err&&<div className="error">{err}</div>}<small>Permanent authority: Tngov@cbe.ac.in</small></div></div>}
function Cards({data}){return <div className="cards">{[['Parcels',data.parcels],['Projects',data.projects],['High Risk',data.high_risk],['Evidence',data.evidence],['Verification Queue',data.verification_pending],['Objections',data.citizen_objections],['Valuation Anomalies',data.valuation_anomalies]].map(x=><div className="card"key={x[0]}><span>{x[0]}</span><b>{x[1]??0}</b></div>)}</div>}
function Parcel({onSaved}){const init={record_id:'',survey_no:'',subdivision:'',village:'',taluk:'',district:'Coimbatore',area:'',classification:'Agricultural',project_id:'',latitude:'11.0168',longitude:'76.9558',training_label:'LOW',project_type:'Road'};const[p,setP]=useState(init),[msg,setMsg]=useState('');const set=(k,v)=>setP({...p,[k]:v});return <section className="panel"><h2>Land Digital Twin • Add Parcel</h2><div className="form">{[['record_id','Record ID'],['survey_no','Survey Number'],['subdivision','Subdivision'],['village','Village'],['taluk','Taluk'],['district','District'],['area','Area (acres)'],['classification','Classification'],['project_id','Project ID'],['latitude','Latitude'],['longitude','Longitude'],['project_type','Project Type']].map(([k,l])=><label key={k}>{l}<input value={p[k]}onChange={e=>set(k,e.target.value)}/></label>)}<label>Training label<select value={p.training_label}onChange={e=>set('training_label',e.target.value)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></label></div><button onClick={async()=>{try{const ml=Object.fromEntries(F.map(k=>[k,Number(p[k]||0)]));const x=await api('/land-records/',{method:'POST',body:JSON.stringify({...p,area:Number(p.area),latitude:Number(p.latitude),longitude:Number(p.longitude),ml_features:ml})});setMsg(`Saved parcel #${x.parcel_id}. Risk ${x.prediction.risk_score}; model ${x.model_version}.`);onSaved()}catch(e){setMsg(e.message)}}}>Validate • Predict • Save • Retrain</button>{msg&&<div className="notice">{msg}</div>}</section>}
function Projects(){const[rows,setRows]=useState([]);useEffect(()=>{api('/projects/').then(setRows).catch(()=>{})},[]);return <section className="panel"><h2>Acquisition Projects</h2><table><thead><tr><th>Project</th><th>Type</th><th>District</th><th>Taluk</th><th>Parcels</th><th>Families</th></tr></thead><tbody>{rows.map(r=><tr key={r.project_id}><td>{r.project_name||r.project_id}</td><td>{r.project_type}</td><td>{r.district}</td><td>{r.taluk}</td><td>{r.affected_parcels}</td><td>{r.affected_families}</td></tr>)}</tbody></table></section>}
function Parcels(){const[rows,setRows]=useState([]);const load=()=>api('/land-records/?limit=100').then(setRows).catch(()=>{});useEffect(load,[]);return <section className="panel"><h2>Parcel Risk Register</h2><button onClick={load}>Refresh</button><table><thead><tr><th>Record</th><th>Survey</th><th>Village</th><th>Project</th><th>Risk</th><th>Score</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.record_id}</td><td>{r.survey_no}/{r.subdivision}</td><td>{r.village}</td><td>{r.project_id}</td><td><strong className={'risk '+String(r.risk_category).toLowerCase()}>{r.risk_category}</strong></td><td>{Number(r.risk_score||0).toFixed(1)}</td></tr>)}</tbody></table></section>}
function MapPanel(){return <section className="panel"><h2>GIS Evidence Layer</h2><p>Bundled GeoJSON is demo evidence only. Do not present it as authoritative cadastral boundaries.</p><div className="map"><iframe title="OpenStreetMap"src="https://www.openstreetmap.org/export/embed.html?bbox=76.75%2C10.75%2C77.2%2C11.25&layer=mapnik"/></div></section>}
function Simulator(){const[out,setOut]=useState(null);return <section className="panel"><h2>Acquisition Flight Simulator</h2><p>Compare Route A/B/C before a decision.</p><button onClick={async()=>setOut(await api('/intelligence/simulate',{method:'POST',body:JSON.stringify({})}))}>Run Simulation</button>{out&&<div className="scenarioGrid">{out.scenarios.map(s=><div className="scenario"key={s.name}><h3>{s.name}{s.name===out.recommended.name?' ★ Recommended':''}</h3><div>Cost: {s.cost.toFixed(1)}</div><div>Affected parcels: {s.affected_parcels}</div><div>High-risk: {s.high_risk}</div><div>Delay: {s.delay_months} months</div><div>Decision score: <b>{s.decision_score}</b></div></div>)}</div>}</section>}
function Tools(){const[res,setRes]=useState(null);const[p,setP]=useState({before:.2,after:.5,threshold:.15});return <section className="panel"><h2>Evidence Intelligence</h2><div className="toolrow"><button onClick={async()=>setRes(await api('/intelligence/satellite/change',{method:'POST',body:JSON.stringify(p)}))}>Check Satellite Change</button><button onClick={async()=>setRes(await api('/intelligence/premortem',{method:'POST',body:JSON.stringify({legal_disputes:1,objections:1,compensation_deviation:18,satellite_change:1})}))}>Run Acquisition Pre-Mortem</button><button onClick={async()=>setRes(await api('/intelligence/conflict-graph'))}>Build Conflict Graph</button></div><div className="form compact">{Object.keys(p).map(k=><label key={k}>{k}<input type="number"step="0.01"value={p[k]}onChange={e=>setP({...p,[k]:e.target.value})}/></label>)}</div>{res&&<pre className="result">{JSON.stringify(res,null,2)}</pre>}</section>}
function Evidence(){const[parcel,setParcel]=useState(''),[reason,setReason]=useState(''),[msg,setMsg]=useState('');return <section className="panel"><h2>Citizen Evidence & Field Verification</h2><div className="form compact"><label>Parcel ID<input value={parcel}onChange={e=>setParcel(e.target.value)}/></label><label>Objection / notes<textarea value={reason}onChange={e=>setReason(e.target.value)}/></label></div><div className="toolrow"><button onClick={async()=>{try{const x=await api('/intelligence/objection',{method:'POST',body:JSON.stringify({parcel_id:parcel,reason})});setMsg(x.message)}catch(e){setMsg(e.message)}}}>Submit Citizen Objection</button><button onClick={async()=>{try{const x=await api('/intelligence/verify',{method:'POST',body:JSON.stringify({parcel_id:parcel,outcome:'verified',notes:reason,latitude:11.0168,longitude:76.9558})});setMsg(x.message)}catch(e){setMsg(e.message)}}}>Field Verify</button><button onClick={async()=>setMsg(JSON.stringify(await api('/intelligence/ledger')))}>Check Evidence Ledger</button></div>{msg&&<pre className="result">{msg}</pre>}</section>}
function OCR(){const[file,setFile]=useState(null),[out,setOut]=useState(null);return <section className="panel"><h2>Document Intelligence</h2><input type="file"onChange={e=>setFile(e.target.files[0])}/><button disabled={!file}onClick={async()=>{const f=new FormData();f.append('file',file);setOut(await api('/intelligence/documents/ocr',{method:'POST',body:f}))}}>Upload & OCR</button>{out&&<pre className="result">{JSON.stringify(out,null,2)}</pre>}</section>}
function Report(){const[id,setId]=useState(''),[out,setOut]=useState(null);return <section className="panel"><h2>Factual Evidence Report</h2><input placeholder="Parcel database ID"value={id}onChange={e=>setId(e.target.value)}/><button onClick={async()=>setOut(await api('/intelligence/report/'+id))}>Generate Report</button>{out&&<pre className="result">{JSON.stringify(out,null,2)}</pre>}</section>}
function Users(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState('officer'),[users,setUsers]=useState([]);const load=()=>api('/auth/users').then(setUsers).catch(()=>{});useEffect(load,[]);return <section className="panel"><h2>Authority User Management</h2><div className="form compact"><input placeholder="Email"value={email}onChange={e=>setEmail(e.target.value)}/><input placeholder="Temporary password"value={password}onChange={e=>setPassword(e.target.value)}/><select value={role}onChange={e=>setRole(e.target.value)}><option>admin</option><option>officer</option><option>field</option><option>citizen</option></select><button onClick={async()=>{await api('/auth/users',{method:'POST',body:JSON.stringify({email,password,role})});load()}}>Create User</button></div><table><thead><tr><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Active':'Disabled'}{u.is_authority?' • PERMANENT':''}</td></tr>)}</tbody></table></section>}

function Advanced(){
 const [fusion,setFusion]=useState(null),[cluster,setCluster]=useState(null),[active,setActive]=useState(null),[fb,setFb]=useState('');
 const runFusion=async()=>setFusion(await api('/intelligence/fusion',{method:'POST',body:JSON.stringify({features:{project_type:'Road',land_required:2,affected_parcels:10,affected_families:3,legal_disputes:1,compensation_pending:1,approval_pending:0,documentation_pending:1,rehabilitation_pending:0,notification_pending:0,award_pending:0,possession_pending:0,stakeholder_responsiveness:2,environmental_risk:1,weather_risk:1},evidence:{satellite_observation:true,satellite_confidence:.86,document_mismatch_count:2,objection_count:2,ownership_complexity:3,data_completeness:72}})}));
 const runActive=async()=>setActive(await api('/intelligence/active-learning',{method:'POST',body:JSON.stringify({parcels:[{parcel_id:'P1048',risk:76,uncertainty:28,missing_evidence:2,connected_parcels:8},{parcel_id:'P102',risk:64,uncertainty:61,missing_evidence:4,connected_parcels:6},{parcel_id:'P103',risk:77,uncertainty:35,missing_evidence:1,connected_parcels:2}]})}));
 return <section className="panel"><h2>Advanced Intelligence • Closed Loop</h2>
 <div className="toolrow"><button onClick={runFusion}>Run Multimodal Fusion</button><button onClick={async()=>setCluster(await api('/intelligence/clusters'))}>Detect Conflict Clusters</button><button onClick={runActive}>Prioritize Field Verification</button></div>
 {fusion&&<div className="notice"><b>Fusion Risk {fusion.risk_score}/100 • {fusion.risk_category}</b><br/>Uncertainty: {fusion.uncertainty}% • Data quality: {fusion.data_quality}%<br/>{fusion.disclaimer}</div>}
 {cluster&&<pre className="result">{JSON.stringify(cluster,null,2)}</pre>}
 {active&&<pre className="result">{JSON.stringify(active,null,2)}</pre>}
 <div className="toolrow"><input placeholder="Predicted label"value={fb}onChange={e=>setFb(e.target.value)}/><button onClick={async()=>setFb(JSON.stringify(await api('/intelligence/feedback',{method:'POST',body:JSON.stringify({parcel_id:1,predicted:fb,ground_truth:'VERIFIED',notes:'Field outcome captured'})})))}>Record Ground Truth</button><button onClick={async()=>setFb(JSON.stringify(await api('/intelligence/model-health')))}>Model Health</button></div>
 {fb&&<pre className="result">{fb}</pre>}
 </section>
}

function App(){const[user,setUser]=useState(null),[dash,setDash]=useState({});const load=()=>api('/intelligence/overview').then(setDash).catch(()=>{});useEffect(()=>{if(localStorage.getItem('survi_token'))api('/auth/me').then(setUser).catch(()=>localStorage.removeItem('survi_token'))},[]);useEffect(()=>{if(user)load()},[user]);if(!user)return <Login onLogin={setUser}/>;return <div className="app"><header><div><div className="brand">SURVI</div><h1>LANDNEXUS</h1><p>Multimodal Early-Warning & Decision Intelligence</p></div><div className="user">{user.role.toUpperCase()} • {user.email}<button className="logout"onClick={()=>{localStorage.removeItem('survi_token');setUser(null)}}>Logout</button></div></header><main><section className="hero"><h2>Command Center</h2><p>Physical reality + administrative reality + citizen reality → evidence fusion → calibrated risk → verification → decision simulation.</p></section><Cards data={dash}/><Projects/><Parcels/><Parcel onSaved={load}/><MapPanel/><Tools/><Simulator/><Evidence/><OCR/><Report/><Advanced/>{user.role==='authority'&&<Users/>}</main></div>}export default App;
